#!/bin/sh

# Check files for PEP-8 compliance

set -e

(
    cd anamorphy_files

    src=$(ls *.py | egrep -v '^(perspective.py|scene.py|geometry.py|constants.py|autogenerated_GUI.py)$')
    echo $src
    pep8 --show-source --repeat $src

    src="perspective.py scene.py geometry.py constants.py"
    echo $src
    pep8 --show-source --repeat --ignore=E201,E221,E241 $src
)
